version: '3.8'

services:
  web:
    build: ./apps/web
    volumes:
      - ./apps/web:/app/
      - /app/node_modules
    ports:
      - '3000:3000'

  feedbacks-service:
    build: ./services/feedbacks
    volumes:
      - ./services/feedbacks:/app/
      - /app/node_modules
    ports:
      - '8003:8003'
    environment:
      PORT: 8003
      AWS_REGION: us-east-1
      MONGO_URI: ${FEEDBACKS_MONGO_URI}
      SQS_QUEUE_URL: ${FEEDBACKS_SQS_QUEUE_URL}

volumes:
  db-data:
