version: '3.8'

services:
  web:
    build: ./apps/web
    volumes:
      - ./apps/web:/app/
      - /app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - feedbacks-service
    environment:
      VITE_EVENTS_SERVICE_DOMAIN: https://2q4va1qw46.execute-api.us-east-1.amazonaws.com/dev
      VITE_TICKETS_SERVICE_DOMAIN: https://j9hxhayim6.execute-api.us-east-1.amazonaws.com/dev
      # VITE_FEEDBACKS_SERVICE_DOMAIN: http://localhost:8003
      VITE_FEEDBACKS_SERVICE_DOMAIN: http://getfeedbacksapp-nvcex.eba-swsxwfmq.us-east-1.elasticbeanstalk.com
      VITE_URL_SHORTENER_SERVICE_URL: http://shortlink.us-east-1.elasticbeanstalk.com/api

  feedbacks-service:
    build: ./services/feedbacks
    volumes:
      - ./services/feedbacks:/app/
      - /app/node_modules
    ports:
      - '8003:8003'
    environment:
      PORT: 8003
      AWS_REGION: us-east-1
      MONGO_URI: ${FEEDBACKS_MONGO_URI}
      SQS_QUEUE_URL: ${FEEDBACKS_SQS_QUEUE_URL}
